import json
import warnings
import peptacular as pt


output_file = 'src/peptacular/fragment/refmol/data.py'


def gen_refmol() -> None:
    """Generate reference molecule data file from JSON"""
    
    print("\n" + "="*60)
    print("GENERATING REFERENCE MOLECULE DATA")
    print("="*60)
    
    print("  📖 Reading from: data_gen/data/mzpaf_reference_molecules.json")
    with open("data_gen/data/mzpaf_reference_molecules.json", "r") as f:
        data = json.load(f)
    
    print(f"  ✓ Parsed {len(data)} reference molecules")
    
    print(f"\n  📝 Writing to: {output_file}")
    
    # Generate enum entries and dictionary entries
    enum_entries: list[str] = []
    literal_entries: list[str] = []
    dict_entries: list[str] = []
    
    for name, info in sorted(data.items()):
        # Convert name to enum format (replace hyphens with underscores, handle special chars)
        enum_name = name.replace('-', '_').replace('+', '_PLUS').upper()
        
        enum_entries.append(f'    {enum_name} = "{name}"')
        literal_entries.append(f'    "{name}",')
        
        # Extract fields
        label_type = info.get("label_type", "")
        molecule_type = info.get("molecule_type", "")
        chemical_formula = info.get("chemical_formula", "")
        
        # Parse formula using ChargedFormula
        formula = None
        composition_dict = {}
        monoisotopic_mass = 0.0
        average_mass = 0.0
        
        if chemical_formula:
            try:
                formula = pt.ChargedFormula.from_string(f"Formula:{chemical_formula}", allow_zero=True)
                
                # Remove any elements with zero count from the composition
                elements = tuple(elem for elem in formula.formula if elem.occurance != 0)
                
                # Check for non-zero charge
                if formula.charge is not None:
                    raise ValueError(f"Non-zero charge in formula: {chemical_formula}")
                
                formula = pt.ChargedFormula(formula=elements, charge=formula.charge)
                composition_dict = formula.get_dict_composition()
                monoisotopic_mass = formula.get_mass(monoisotopic=True)
                average_mass = formula.get_mass(monoisotopic=False)
                
            except Exception as e:
                warnings.warn(f"Error parsing formula for {name}: {chemical_formula}, {e}")
        
        # Override with provided masses if available
        if "neutral_mass" in info:
            provided_mass = info["neutral_mass"]
            if monoisotopic_mass != 0.0 and abs(provided_mass - monoisotopic_mass) > 0.01:

                symbol = '🔴' if abs(provided_mass - monoisotopic_mass) > 1.0 else '⚠️'

                warnings.warn(
                    f"\n  {symbol}  REFMOL MASS MISMATCH: {name} | NEUTRAL MASS\n"
                    f"      Calculated: {monoisotopic_mass:.6f}, Provided: {provided_mass:.6f}\n"
                    f"      Difference: {abs(provided_mass - monoisotopic_mass):.6f}\n"
                    f"      Composition: {composition_dict}"
                )

        if "ion_mz" in info:
            # For ions, subtract proton mass to get neutral mass
            provided_mz = info["ion_mz"]
            neutral_mass = provided_mz - pt.PROTON_MASS
            if monoisotopic_mass != 0.0 and abs(neutral_mass - monoisotopic_mass) > 0.01:

                symbol = '🔴' if abs(neutral_mass - monoisotopic_mass) > 1.0 else '⚠️'


                warnings.warn(
                    f"\n  {symbol}  REFMOL MASS MISMATCH: {name} | ION M/Z\n"
                    f"      Calculated: {monoisotopic_mass:.6f}, Ion m/z: {neutral_mass:.6f}\n"
                    f"      Difference: {abs(neutral_mass - monoisotopic_mass):.6f}\n"
                    f"      Composition: {composition_dict}"
                )
        
        dict_entry = f'''RefMolID.{enum_name}: RefMolInfo(
    name="{name}",
    label_type="{label_type}",
    molecule_type="{molecule_type}",
    chemical_formula='{chemical_formula}',
    monoisotopic_mass={monoisotopic_mass},
    average_mass={average_mass},
    dict_composition={composition_dict},
),'''
        dict_entries.append(dict_entry)
    
    enum_str = '\n'.join(enum_entries)
    literal_str = '\n'.join(literal_entries)
    dict_str = '\n'.join(dict_entries)
    
    # Write the complete file
    content = f'''"""Auto-generated reference molecule data"""
# DO NOT EDIT - generated by gen_refmol.py

from enum import StrEnum
from typing import Literal
from .dclass import RefMolInfo


class RefMolID(StrEnum):
    """Enum of reference molecule IDs"""
{enum_str}


RefMolLiteral = Literal[
{literal_str}
]


REFMOL_DICT: dict[RefMolID, RefMolInfo] = {{
{dict_str}
}}
'''
    
    with open(output_file, 'w') as f:
        f.write(content)
    
    print(f"✅ Successfully generated {output_file}")
    print(f"   Total entries: {len(data)}")


if __name__ == "__main__":
    gen_refmol()
