import json


def gen_proteases() -> None:
    """Generate protease data file from JSON"""
    
    with open("data_gen/data/proteases.json", "r") as f:
        data = json.load(f)
    
    proteases_data = data["proteases"]
    print(f"Found {len(proteases_data)} proteases")
    
    output_file = 'src/peptacular/digestion/data.py'
    print(f"Writing to {output_file}...")
    
    # Generate StrEnum entries
    enum_entries: list[str] = []
    for protease_dict in proteases_data:
        protease_id = protease_dict["id"]
        # Convert id to uppercase enum name
        enum_name = protease_id.upper()
        enum_entries.append(f'    {enum_name} = "{protease_id}"')
    
    enum_str = '\n'.join(enum_entries)
    
    # Generate Literal type entries
    literal_entries: list[str] = []
    for protease_dict in proteases_data:
        protease_id = protease_dict["id"]
        literal_entries.append(f'    "{protease_id}",')
    
    literal_str = '\n'.join(literal_entries)
    
    # Generate the protease dictionary entries
    entries: list[str] = []
    for protease_dict in proteases_data:
        # Use single quotes for regex string
        regex_str = protease_dict["regex_pattern"]
        protease_id = protease_dict["id"]
        enum_name = protease_id.upper()
        
        entry = f'''Proteases.{enum_name}: ProteaseInfo(
    id=Proteases.{enum_name},
    name="{protease_dict["name"]}",
    full_name="{protease_dict["full_name"]}",
    regex='{regex_str}',
),'''
        entries.append(entry)
    
    entries_str = '\n'.join(entries)
    
    # Write the complete file
    content = f'''"""Auto-generated protease data"""
# DO NOT EDIT - generated by gen_proteases_obo.py

from typing import Literal
from enum import StrEnum

from .dclass import ProteaseInfo

class Proteases(StrEnum):
    """Enum of protease IDs"""
{enum_str}

PROTEASE_LITERALS = Literal[
{literal_str}
]


PROTEASES_DICT: dict[Proteases, ProteaseInfo] = {{
{entries_str}
}}
'''
    
    with open(output_file, 'w') as f:
        f.write(content)
    
    print(f"✅ Successfully generated {output_file}")
    print(f"   Total entries: {len(proteases_data)}")


if __name__ == "__main__":
    gen_proteases()
